/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind23_slowrenju_GlobalValue */

#ifndef _Included_com_wind23_slowrenju_GlobalValue
#define _Included_com_wind23_slowrenju_GlobalValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind23_slowrenju_GlobalValue
 * Method:    getPos
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_com_wind23_slowrenju_GlobalValue_getPos
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_wind23_slowrenju_GlobalValue
 * Method:    testWin
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_com_wind23_slowrenju_GlobalValue_testWin
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_wind23_slowrenju_GlobalValue
 * Method:    stopThink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wind23_slowrenju_GlobalValue_stopThink
  (JNIEnv *, jclass);

/*
* Class:     com_wind23_slowrenju_GlobalValue
* Method:    thinkingStatus
* Signature: ()Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_com_wind23_slowrenju_GlobalValue_thinkingStatus
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
